### ISSUE TITLE
El código no debe ir en el readme.md

### ISSUE THREAD

**Issue by LarreaMikel** [daniode12/chess-engine#1]
Hola,
Me parece que has subido el código al fichero readme.md. No es la forma correcta de hacerlo, en este fichero solamente debes explicar los pormenores del proyecto, o lo que te apetezca. Se escribe en markdown ([link](https://guides.github.com/features/mastering-markdown/))

Crea otro fichero en tu carpeta local que sea el fichero .py o .ipynb (si es un notebook) y en él sí que debes pegar el código. De este modo te quedarán dos ficheros en el repositorio.

Un saludo.

**Comment by daniode12** [comment]
Solucionado con el último commit.
